//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeFaceDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attraction
    {
        public int Id { get; set; }
        public System.DateTime DateUTC { get; set; }
        public string Emotion { get; set; }
        public double Attention_time { get; set; }
        public int PersonId { get; set; }
        public int ProjectId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Project Project { get; set; }
    }
}
